### ISSUE TITLE
Website is boring. 

### ISSUE THREAD

**Issue by quindariuss** [dfoskey88/dfoskey#1]
Let's make this website way cooler. 

- [x] Add an image of yourself to the website. 
- [x] Change the background color
- [x] Make a table with your school schedule
- [x] Put your favorite meme under the schedule 

Easy stuff! 
Would make the website have a bit more character.

**Comment by dfoskey88** [comment]
This looks fun! I’ll lyk when I’m done.

**Comment by quindariuss** [comment]
So much better thanks!
